// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokerPuzzleData.DB;

#nullable disable

namespace PokerPuzzleData.Migrations
{
    [DbContext(typeof(PokerPuzzleContext))]
    [Migration("20260124174821_AddedIsFavoriteToGameEntity")]
    partial class AddedIsFavoriteToGameEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("PokerPuzzleData.DB.Entity.ActionEntity", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActionType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerPosition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Street")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameId", "OrderIndex");

                    b.ToTable("Actions");
                });

            modelBuilder.Entity("PokerPuzzleData.DB.Entity.CommunityCardsEntity", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Flop1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Flop2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Flop3")
                        .HasColumnType("TEXT");

                    b.Property<int>("FlopPotSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("River")
                        .HasColumnType("TEXT");

                    b.Property<int>("RiverPotSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShowdownPotSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Turn")
                        .HasColumnType("TEXT");

                    b.Property<int>("TurnPotSize")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameId");

                    b.ToTable("CommunityCards");
                });

            modelBuilder.Entity("PokerPuzzleData.DB.Entity.GameCommentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameId")
                        .IsUnique();

                    b.ToTable("GameComments");
                });

            modelBuilder.Entity("PokerPuzzleData.DB.Entity.GameEntity", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalGameId")
                        .HasColumnType("TEXT");

                    b.Property<int>("FinalPot")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasFlop")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasShowdown")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumPlayers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("isFavorite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.HasKey("GameId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("PokerPuzzleData.DB.Entity.PlayerEntity", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Card1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Card2")
                        .HasColumnType("TEXT");

                    b.HasKey("GameId", "Position");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("PokerPuzzleData.DB.Entity.ActionEntity", b =>
                {
                    b.HasOne("PokerPuzzleData.DB.Entity.GameEntity", "Game")
                        .WithMany("Actions")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("PokerPuzzleData.DB.Entity.CommunityCardsEntity", b =>
                {
                    b.HasOne("PokerPuzzleData.DB.Entity.GameEntity", "Game")
                        .WithOne("CommunityCards")
                        .HasForeignKey("PokerPuzzleData.DB.Entity.CommunityCardsEntity", "GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("PokerPuzzleData.DB.Entity.GameCommentEntity", b =>
                {
                    b.HasOne("PokerPuzzleData.DB.Entity.GameEntity", "Game")
                        .WithOne("GameComment")
                        .HasForeignKey("PokerPuzzleData.DB.Entity.GameCommentEntity", "GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("PokerPuzzleData.DB.Entity.PlayerEntity", b =>
                {
                    b.HasOne("PokerPuzzleData.DB.Entity.GameEntity", "Game")
                        .WithMany("Players")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("PokerPuzzleData.DB.Entity.GameEntity", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("CommunityCards")
                        .IsRequired();

                    b.Navigation("GameComment")
                        .IsRequired();

                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
